Break circular import (#1639)
Sometime I'm seeing this:

```
ImportError while loading conftest '/home/runner/work/iceberg-python/iceberg-python/tests/conftest.py'.
tests/conftest.py:52: in <module>
    from pyiceberg.catalog import Catalog, load_catalog
pyiceberg/catalog/__init__.py:51: in <module>
    from pyiceberg.serializers import ToOutputFile
pyiceberg/serializers.py:25: in <module>
    from pyiceberg.table.metadata import TableMetadata, TableMetadataUtil
pyiceberg/table/__init__.py:65: in <module>
    from pyiceberg.io.pyarrow import ArrowScan, schema_to_pyarrow
pyiceberg/io/pyarrow.py:141: in <module>
    from pyiceberg.table.locations import load_location_provider
pyiceberg/table/locations.py:25: in <module>
    from pyiceberg.table import TableProperties
E   ImportError: cannot import name 'TableProperties' from partially initialized module 'pyiceberg.table' (most likely due to a circular import) (/home/runner/work/iceberg-python/iceberg-python/pyiceberg/table/__init__.py)
```

Also observed in: https://github.com/apache/iceberg-python/pull/1388

I prefer the imports at the top, but I think this is a small price to
pay to avoid having circular imports.