Support quoted column identifiers for scan `row_filter` (#1863)
# Rationale for this change
Our data lake uses old-school Kimball style quoted column names ("User
ID", "Customer Name" etc). The string parser for `row_filter` was unable
to parse this. Now it is.

example: 
```python

# before 
>> parser.parse(' "User Name" = 'ted')
ParseException: Expected '"', found ' '

# after
>> parser.parse(' "User Name" = 'ted')
EqualTo("User Name", "ted")

# Are these changes tested?
Yes a new test was added. 
```

>[!NOTE]
> The `quoted_column_with_dots` previously errored `with "Expected '"',
found '.'"` _when using **double quotes only**_. It now raises error
text expecting an `'or'` value; I didn't toil over finding where the
exception is clobbered, because the error message between single and
double quote exceptions is inconsistent and I didn't really consider
this a polished/first-class error message. If this change is an issue, I
can dig further to try and revert the wording change; IMO raising the
same exception type is more than reasonable to consider the change
non-breaking.

# Are there any user-facing changes?
Yes quoted identifiers are now supported