mypy: Ignore missing annotations globally (#2704)
Weirdly, this also showed some new issues:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1
  mkdocs/gen_doc_stubs.py:20: error: Unused "type: ignore" comment  [unused-ignore]
  mkdocs/gen_doc_stubs.py:21: error: Unused "type: ignore" comment  [unused-ignore]
  tests/utils/test_manifest.py:51: error: "Callable[[FileIO, str], tuple[ManifestFile, ...]]" has no attribute "cache_clear"  [attr-defined]
  tests/conftest.py:101: error: Unused "type: ignore" comment  [unused-ignore]
  Found 4 errors in 3 files (checked 166 source files)
```

<!--
Thanks for opening a pull request!
-->

<!-- In the case this PR will resolve an issue, please replace
${GITHUB_ISSUE_ID} below with the actual Github issue id. -->
<!-- Closes #${GITHUB_ISSUE_ID} -->

# Rationale for this change

## Are these changes tested?

## Are there any user-facing changes?

<!-- In the case of user-facing changes, please add the changelog label.
-->

---------

Co-authored-by: Kevin Liu <kevinjqliu@users.noreply.github.com>
Co-authored-by: Kevin Liu <kevin.jq.liu@gmail.com>