mypy: Ignore missing annotations globally
Weirdly, this also showed some new issues:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1
  mkdocs/gen_doc_stubs.py:20: error: Unused "type: ignore" comment  [unused-ignore]
  mkdocs/gen_doc_stubs.py:21: error: Unused "type: ignore" comment  [unused-ignore]
  tests/utils/test_manifest.py:51: error: "Callable[[FileIO, str], tuple[ManifestFile, ...]]" has no attribute "cache_clear"  [attr-defined]
  tests/conftest.py:101: error: Unused "type: ignore" comment  [unused-ignore]
  Found 4 errors in 3 files (checked 166 source files)
```