fix: handle empty HEAD response (#3041)
# Rationale for this change
HEAD responses return with an empty body, therefore when we try to use
pydantic to parse the json body, it fails on an empty string. This
bypasses pydantic if the body does not exist.

Before:
```
RESTError 403: Received unexpected JSON Payload: , errors: Invalid JSON: EOF while parsing a value at line 1 column 0
```

After:
```
ForbiddenError: RestError: Forbidden
```

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

---------

Co-authored-by: Kevin Liu <kevinjqliu@users.noreply.github.com>