Snapshots are not being transacted on, but need to re-assign refs
 ValueError: Cannot expire snapshot IDs {3051729675574597004} as they are currently referenced by table refs.