sync cibuildwheel test env with uv (#2913)
<!--
Thanks for opening a pull request!
-->

<!-- In the case this PR will resolve an issue, please replace
${GITHUB_ISSUE_ID} below with the actual Github issue id. -->
<!-- Closes #${GITHUB_ISSUE_ID} -->

# Rationale for this change
Follow up to #2912

CI still fails with

https://github.com/apache/iceberg-python/actions/runs/21004478697/job/60383069033
```
Error: cibuildwheel: Command ['C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-0tbpuziz\\cp310-win_amd64\\venv-test\\Scripts\\pip.EXE', 'install', 'pytest==7.4.2', 'moto==5.0.1', 'pytest-lazy-fixture==0.6.3', 'sqlalchemy>=2.0.18,<3'] failed with code 1. 

Error: Process completed with exit code 1.
```

This PR fixes syncs the env with uv so we dont need to explicitly
specify the deps here

## Are these changes tested?
Yes 
https://github.com/apache/iceberg-python/actions/runs/21007310527

## Are there any user-facing changes?

<!-- In the case of user-facing changes, please add the changelog label.
-->